### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chr15m** [mnmmt/device-phonon#1]
* [ ] Get sync -> MIDI protocol finalized.
 * [ ] Clojure/ferret port.
 * [x] Packaging.
 * [x] Only have the URL in shipped media - other instructions in app.
 * [ ] Finish [/hello](https://bzzt.studio/hello) test page:
   * [ ] Emulate the actual device on the screen (with virtual switching visualisation).
   * [ ] Fit whole testing UI on one screen.
   * [ ] "This knob/button is midi assignable."

### From Tomas Ford

 * [ ] Do not send rack selection buttons (interferes with MIDI learn).
 * [ ] Rate limit MIDI messages.
 * [ ] Keep 3rd button independent of rack position.
